[book]
title = "Lira Programming Language"
authors = ["Lira Contributors"]
language = "en"

[build]
build-dir = "book"

[output.html]
default-theme = "ayu"
preferred-dark-theme = "ayu"
git-repository-url = "https://github.com/HelgeSverre/lira"
