//! End-to-end regressions for `name @ pattern` value semantics.

use lira_core::opcode::Opcode;

fn compile_and_run(source: &str) -> (Vec<u8>, Vec<String>) {
    let bytecode = lirac::compile(source).unwrap_or_else(|error| panic!("compile source: {error}"));
    let (status, output) =
        liravm::run_with_capture(&bytecode).unwrap_or_else(|error| panic!("run source: {error}"));
    assert_eq!(status, 0, "source exited with status {status}");
    (bytecode, output)
}

#[test]
fn binding_pattern_copies_the_whole_struct_before_destructuring() {
    let (bytecode, output) = compile_and_run(
        r#"
struct Point { value: int }

let original = Point { value: 1 }
match original {
    whole @ _ => {
        whole.value = 9
        println(whole.value)
        println(original.value)
    }
}
"#,
    );

    assert_eq!(output, ["9", "1"]);

    let program = liravm::bytecode::load(&bytecode).expect("load generated bytecode");
    assert!(
        program.code.contains(&(Opcode::CopyValue as u8)),
        "binding-pattern bytecode must preserve the value-copy boundary"
    );
}

#[test]
fn nested_binding_patterns_keep_the_inner_subject_available() {
    let (_, output) = compile_and_run(
        r#"
struct Point { value: int }

let original = (Point { value: 1 }, 2)
match original {
    whole @ (point @ _, 2) => {
        whole[0].value = 9
        println(point.value)
        println(original[0].value)
    }
    _ => println(0)
}
"#,
    );

    assert_eq!(output, ["1", "1"]);
}
