//! Native regex runtime for code generated by Lira's native backend.
//!
//! The exported functions deliberately keep allocation and ownership in the C
//! runtime. Rust only borrows incoming strings for the duration of a call;
//! returned strings and arrays are made with `lira_rt_str_new` and
//! `lira_rt_array_new`/`lira_rt_array_push`.

#![allow(clippy::not_unsafe_ptr_arg_deref)]

include!(concat!(env!("OUT_DIR"), "/archive_marker.rs"));

mod http;
mod json;

pub use http::{lira_rt_http_get, lira_rt_http_post, lira_rt_http_request};
pub use json::{lira_rt_json_parse, lira_rt_json_stringify, lira_rt_json_stringify_pretty};

use regex::{Captures, Regex, RegexBuilder};
use std::ffi::c_char;
use std::panic::{catch_unwind, AssertUnwindSafe};
use std::slice;
use std::str;

const LIRA_KIND_STRING: u32 = 1;
const MAX_ABI_BYTES: i64 = isize::MAX as i64 - 24;

// Regex operations are bounded so a program cannot turn one builtin call into
// an unaccounted allocation storm. These values are part of the native ABI's
// observable safety contract and must stay in sync with liravm::runtime.
const MAX_REGEX_PATTERN_BYTES: usize = 64 * 1024;
const MAX_REGEX_INPUT_BYTES: usize = 16 * 1024 * 1024;
const MAX_REGEX_RESULT_COUNT: usize = 100_000;
const MAX_REGEX_OUTPUT_BYTES: usize = 32 * 1024 * 1024;
const MAX_REGEX_COMPILED_BYTES: usize = 8 * 1024 * 1024;

/// Header common to all heap objects in the native ABI.
#[repr(C)]
#[derive(Debug, Clone, Copy)]
pub struct LiraHeader {
    pub kind: u32,
    pub flags: u32,
    pub rc: i64,
}

/// Native string object. `data` is a C flexible-array tail represented by one
/// byte for layout purposes; the actual allocation is owned by the runtime.
#[repr(C)]
#[derive(Debug)]
pub struct LiraStr {
    pub hdr: LiraHeader,
    pub len: i64,
    pub data: [u8; 1],
}

/// Array storage is intentionally opaque: only the runtime that allocated it
/// may inspect or mutate its fields.
#[repr(C)]
pub struct LiraArray {
    _private: [u8; 0],
}

/// Uniformly boxed dynamic value used by the C runtime.
#[repr(C)]
pub struct LiraAny {
    pub hdr: LiraHeader,
    pub tag: i64,
    pub payload: u64,
}

extern "C" {
    fn lira_rt_str_new(bytes: *const c_char, len: i64) -> *mut LiraStr;
    fn lira_rt_array_new(cap: i64) -> *mut LiraArray;
    fn lira_rt_array_push(array: *mut LiraArray, value: i64);
    fn lira_rt_panic(message: *const c_char);
}

/// Borrow a string supplied by the native ABI.
///
/// # Safety
///
/// `value` must point to a live `LiraStr` allocation whose flexible tail has
/// at least `len` bytes. The generated runtime owns those allocations and
/// keeps them live for the duration of each call.
unsafe fn read_str<'a>(value: *const LiraStr) -> Option<&'a str> {
    if value.is_null() {
        return None;
    }
    if !(value as usize).is_multiple_of(std::mem::align_of::<LiraStr>()) {
        return None;
    }
    // A malformed length must be rejected before pointer arithmetic. The
    // native ABI promises a live allocation containing this many bytes; this
    // check prevents integer overflow and impossible slices at the boundary.
    let kind = (*value).hdr.kind;
    let len = (*value).len;
    if !(0..=MAX_ABI_BYTES).contains(&len) || kind != LIRA_KIND_STRING {
        return None;
    }
    let bytes = slice::from_raw_parts((*value).data.as_ptr(), len as usize);
    str::from_utf8(bytes).ok()
}

unsafe fn call_str_new(value: &str) -> *mut LiraStr {
    // `str` is UTF-8 and remains borrowed until the helper returns.
    lira_rt_str_new(value.as_ptr().cast::<c_char>(), value.len() as i64)
}

unsafe fn call_array_new(capacity: usize) -> *mut LiraArray {
    lira_rt_array_new(capacity.min(i64::MAX as usize) as i64)
}

unsafe fn push_str(array: *mut LiraArray, value: &str) {
    let string = call_str_new(value);
    lira_rt_array_push(array, string.cast::<()>() as usize as i64);
}

unsafe fn panic_runtime(message: &str) {
    // `lira_rt_panic` takes a conventional NUL-terminated C string (unlike
    // `lira_rt_str_new`, which takes an explicit length).
    let mut nul_terminated = Vec::with_capacity(message.len() + 1);
    nul_terminated.extend_from_slice(message.as_bytes());
    nul_terminated.push(0);
    lira_rt_panic(nul_terminated.as_ptr().cast::<c_char>());
}

fn invalid_abi() {
    // Invalid pointers are an ABI violation, not a user-level regex error.
    unsafe { panic_runtime("invalid Lira string") }
}

fn fallback_str(value: Option<&str>) -> *mut LiraStr {
    // The fallback is itself within the export's catch_unwind closure.
    unsafe { call_str_new(value.unwrap_or_default()) }
}

fn fallback_array(values: &[&str]) -> *mut LiraArray {
    unsafe {
        let array = call_array_new(values.len());
        for value in values {
            push_str(array, value);
        }
        array
    }
}

fn with_bool(operation: impl FnOnce() -> bool) -> i8 {
    match catch_unwind(AssertUnwindSafe(operation)) {
        Ok(value) => value as i8,
        Err(_) => {
            unsafe { panic_runtime("regex runtime panic") };
            0
        }
    }
}

fn with_str(operation: impl FnOnce() -> *mut LiraStr) -> *mut LiraStr {
    match catch_unwind(AssertUnwindSafe(operation)) {
        Ok(value) => value,
        Err(_) => {
            unsafe { panic_runtime("regex runtime panic") };
            fallback_str(None)
        }
    }
}

fn with_array(operation: impl FnOnce() -> *mut LiraArray) -> *mut LiraArray {
    match catch_unwind(AssertUnwindSafe(operation)) {
        Ok(value) => value,
        Err(_) => {
            unsafe { panic_runtime("regex runtime panic") };
            fallback_array(&[])
        }
    }
}

fn build_regex(pattern: &str) -> Option<Regex> {
    if pattern.len() > MAX_REGEX_PATTERN_BYTES {
        return None;
    }
    RegexBuilder::new(pattern)
        .size_limit(MAX_REGEX_COMPILED_BYTES)
        .dfa_size_limit(MAX_REGEX_COMPILED_BYTES)
        .build()
        .ok()
}

fn valid_input(pattern: &str, text: &str) -> bool {
    pattern.len() <= MAX_REGEX_PATTERN_BYTES && text.len() <= MAX_REGEX_INPUT_BYTES
}

fn push_bounded(output: &mut String, value: &str) -> bool {
    let Some(next_len) = output.len().checked_add(value.len()) else {
        return false;
    };
    if next_len > MAX_REGEX_OUTPUT_BYTES {
        return false;
    }
    output.push_str(value);
    true
}

fn capture_reference<'a>(captures: &'a Captures<'_>, reference: &str) -> Option<&'a str> {
    if let Ok(index) = reference.parse::<usize>() {
        return captures.get(index).map(|capture| capture.as_str());
    }
    captures.name(reference).map(|capture| capture.as_str())
}

/// Append a regex replacement using the same `$name`, `${name}`, `$0`, and
/// `$$` rules as `regex::Captures::expand`, while checking every append.
fn push_replacement(captures: &Captures<'_>, replacement: &str, output: &mut String) -> bool {
    let mut remaining = replacement;
    while !remaining.is_empty() {
        let Some(dollar) = remaining.find('$') else {
            return push_bounded(output, remaining);
        };
        if !push_bounded(output, &remaining[..dollar]) {
            return false;
        }
        remaining = &remaining[dollar..];
        if remaining.as_bytes().get(1) == Some(&b'$') {
            if !push_bounded(output, "$") {
                return false;
            }
            remaining = &remaining[2..];
            continue;
        }

        let bytes = remaining.as_bytes();
        let (reference, end) = if bytes.get(1) == Some(&b'{') {
            let Some(close) = remaining[2..].find('}') else {
                if !push_bounded(output, "$") {
                    return false;
                }
                remaining = &remaining[1..];
                continue;
            };
            let end = close + 3;
            (&remaining[2..end - 1], end)
        } else {
            let mut end = 1;
            while bytes
                .get(end)
                .is_some_and(|byte| byte.is_ascii_alphanumeric() || *byte == b'_')
            {
                end += 1;
            }
            if end == 1 {
                if !push_bounded(output, "$") {
                    return false;
                }
                remaining = &remaining[1..];
                continue;
            }
            (&remaining[1..end], end)
        };
        if let Some(value) = capture_reference(captures, reference) {
            if !push_bounded(output, value) {
                return false;
            }
        }
        remaining = &remaining[end..];
    }
    true
}

fn bounded_replace(regex: &Regex, text: &str, replacement: &str, all: bool) -> Option<String> {
    let mut output = String::new();
    let mut last_match = 0;
    for (match_count, captures) in regex.captures_iter(text).enumerate() {
        if match_count >= MAX_REGEX_RESULT_COUNT {
            return None;
        }
        let full_match = captures.get(0)?;
        if !push_bounded(&mut output, &text[last_match..full_match.start()])
            || !push_replacement(&captures, replacement, &mut output)
        {
            return None;
        }
        last_match = full_match.end();
        if !all {
            break;
        }
    }
    if !push_bounded(&mut output, &text[last_match..]) {
        return None;
    }
    Some(output)
}

/// Return whether `text` contains a match for `pattern`; invalid patterns and
/// malformed ABI values return false.
#[no_mangle]
pub extern "C" fn lira_rt_regex_match(pattern: *const LiraStr, text: *const LiraStr) -> i8 {
    with_bool(|| unsafe {
        match (read_str(pattern), read_str(text)) {
            (Some(pattern), Some(text)) => {
                valid_input(pattern, text)
                    && build_regex(pattern).is_some_and(|regex| regex.is_match(text))
            }
            _ => {
                invalid_abi();
                false
            }
        }
    })
}

/// Return the first match, or an empty string when there is no match.
#[no_mangle]
pub extern "C" fn lira_rt_regex_find(
    pattern: *const LiraStr,
    text: *const LiraStr,
) -> *mut LiraStr {
    with_str(|| unsafe {
        match (read_str(pattern), read_str(text)) {
            (Some(pattern), Some(text)) => {
                if !valid_input(pattern, text) {
                    fallback_str(Some(""))
                } else {
                    build_regex(pattern)
                        .and_then(|regex| regex.find(text).map(|m| m.as_str()))
                        .map_or_else(|| fallback_str(Some("")), |value| fallback_str(Some(value)))
                }
            }
            _ => {
                invalid_abi();
                fallback_str(Some(""))
            }
        }
    })
}

/// Return all non-overlapping matches in order, or an empty array on error.
#[no_mangle]
pub extern "C" fn lira_rt_regex_find_all(
    pattern: *const LiraStr,
    text: *const LiraStr,
) -> *mut LiraArray {
    with_array(|| unsafe {
        match (read_str(pattern), read_str(text)) {
            (Some(pattern), Some(text)) => {
                if !valid_input(pattern, text) {
                    fallback_array(&[])
                } else {
                    build_regex(pattern).map_or_else(
                        || fallback_array(&[]),
                        |regex| {
                            let count = regex
                                .find_iter(text)
                                .take(MAX_REGEX_RESULT_COUNT + 1)
                                .count();
                            if count > MAX_REGEX_RESULT_COUNT {
                                return fallback_array(&[]);
                            }
                            let array = call_array_new(count);
                            for value in regex.find_iter(text) {
                                push_str(array, value.as_str());
                            }
                            array
                        },
                    )
                }
            }
            _ => {
                invalid_abi();
                fallback_array(&[])
            }
        }
    })
}

/// Replace the first occurrence, preserving the input on an invalid pattern.
#[no_mangle]
pub extern "C" fn lira_rt_regex_replace(
    pattern: *const LiraStr,
    text: *const LiraStr,
    replacement: *const LiraStr,
) -> *mut LiraStr {
    with_str(|| unsafe {
        match (read_str(pattern), read_str(text), read_str(replacement)) {
            (Some(pattern), Some(text), Some(replacement)) => {
                if !valid_input(pattern, text) || replacement.len() > MAX_REGEX_INPUT_BYTES {
                    call_str_new(text)
                } else {
                    let result = build_regex(pattern)
                        .and_then(|regex| bounded_replace(&regex, text, replacement, false))
                        .unwrap_or_else(|| text.to_owned());
                    call_str_new(&result)
                }
            }
            _ => {
                invalid_abi();
                fallback_str(Some(""))
            }
        }
    })
}

/// Replace all occurrences, preserving the input on an invalid pattern.
#[no_mangle]
pub extern "C" fn lira_rt_regex_replace_all(
    pattern: *const LiraStr,
    text: *const LiraStr,
    replacement: *const LiraStr,
) -> *mut LiraStr {
    with_str(|| unsafe {
        match (read_str(pattern), read_str(text), read_str(replacement)) {
            (Some(pattern), Some(text), Some(replacement)) => {
                if !valid_input(pattern, text) || replacement.len() > MAX_REGEX_INPUT_BYTES {
                    call_str_new(text)
                } else {
                    let result = build_regex(pattern)
                        .and_then(|regex| bounded_replace(&regex, text, replacement, true))
                        .unwrap_or_else(|| text.to_owned());
                    call_str_new(&result)
                }
            }
            _ => {
                invalid_abi();
                fallback_str(Some(""))
            }
        }
    })
}

/// Split text by a regex; invalid patterns return one element containing text.
#[no_mangle]
pub extern "C" fn lira_rt_regex_split(
    pattern: *const LiraStr,
    text: *const LiraStr,
) -> *mut LiraArray {
    with_array(|| unsafe {
        match (read_str(pattern), read_str(text)) {
            (Some(pattern), Some(text)) => {
                if !valid_input(pattern, text) {
                    fallback_array(&[text])
                } else {
                    build_regex(pattern).map_or_else(
                        || fallback_array(&[text]),
                        |regex| {
                            let count = regex.split(text).take(MAX_REGEX_RESULT_COUNT + 1).count();
                            if count > MAX_REGEX_RESULT_COUNT {
                                return fallback_array(&[text]);
                            }
                            let array = call_array_new(count);
                            for value in regex.split(text) {
                                push_str(array, value);
                            }
                            array
                        },
                    )
                }
            }
            _ => {
                invalid_abi();
                fallback_array(&[])
            }
        }
    })
}

/// Return full match followed by present capture groups from the first match.
#[no_mangle]
pub extern "C" fn lira_rt_regex_captures(
    pattern: *const LiraStr,
    text: *const LiraStr,
) -> *mut LiraArray {
    with_array(|| unsafe {
        match (read_str(pattern), read_str(text)) {
            (Some(pattern), Some(text)) => {
                if !valid_input(pattern, text) {
                    fallback_array(&[])
                } else {
                    build_regex(pattern).map_or_else(
                        || fallback_array(&[]),
                        |regex| {
                            regex.captures(text).map_or_else(
                                || fallback_array(&[]),
                                |captures| {
                                    let mut count = 0;
                                    let mut total_bytes = 0usize;
                                    for capture in captures.iter().flatten() {
                                        let Some(next_bytes) =
                                            total_bytes.checked_add(capture.as_str().len())
                                        else {
                                            return fallback_array(&[]);
                                        };
                                        if next_bytes > MAX_REGEX_OUTPUT_BYTES
                                            || count == MAX_REGEX_RESULT_COUNT
                                        {
                                            return fallback_array(&[]);
                                        }
                                        total_bytes = next_bytes;
                                        count += 1;
                                    }
                                    if count > MAX_REGEX_RESULT_COUNT {
                                        return fallback_array(&[]);
                                    }
                                    let array = call_array_new(count);
                                    for capture in captures.iter().flatten() {
                                        push_str(array, capture.as_str());
                                    }
                                    array
                                },
                            )
                        },
                    )
                }
            }
            _ => {
                invalid_abi();
                fallback_array(&[])
            }
        }
    })
}

/// Return whether `pattern` compiles as a regex.
#[no_mangle]
pub extern "C" fn lira_rt_regex_is_valid(pattern: *const LiraStr) -> i8 {
    with_bool(|| unsafe {
        match read_str(pattern) {
            Some(pattern) => build_regex(pattern).is_some(),
            None => {
                invalid_abi();
                false
            }
        }
    })
}

#[cfg(test)]
mod tests;
