[package]
name = "lira"
version = "0.1.0"
edition = "2021"
rust-version.workspace = true
description = "Lira programming language CLI"
license = "MIT"

[[bin]]
name = "lira"
path = "src/main.rs"

[dependencies]
lirac = { path = "../lirac", features = ["serde"] }
liravm = { path = "../liravm" }
lira-core = { path = "../lira-core" }
lira-codegen = { path = "../lira-codegen" }
